package com.example.demo.domain;

import com.alibaba.fastjson.JSON;
import lombok.Data;

import java.util.List;

@Data
public class Student {

    int id;
    String name;

    public static void main(String[] args) {
        String t1 = "[\"LOD_JCW67_CS94_DMRZR_CASHLOANSC_B_CARD_SCORE_TRACEBACK_I_D\",\"LOD_JCW67_CS94_DMRZR_DTEST_CASH_LOAN_AUTO_OUTPUT_I_D\",\"LOD_JCW67_CS94_DMRZR_COMBINCARD_CREDIT_CARD_SCORE_AUTOBACK_I_D\",\"LOD_JCW67_CS94_DMRZR_ZEBRAV2_CF_XBXYFX_SOCIAL_RISK_SCORE_AUTOBACK_I_D\",\"LOD_JCW67_CS94_DMRZR_DTEST_BLACK_LIST_V2_AUTO_OUTPUT_I_D\",\"LOD_JCW67_CS94_DMRZR_GDJ_MODEL_FTC_OUTPUT_I_D\",\"LOD_JCW67_CS94_DMRZR_DTEST_KEQUN_LABEL_AUTO_OUTPUT_I_D\",\"LOD_JCW67_CS9_JRM_MULTI_LOAN_OUTPUT_PARAM_HS_I_D\",\"LOD_JCW67_CS9_JRM_CREDIT_PORTRAIT_OUTPUT_PARAM_HS_I_D\",\"LOD_JCW67_CS4_JRM_PANGUV3_SCORE_OUTPUT_PARAM_HS_I_D\",\"LOD_JCW67_CS4_MULTIPLE_V3_SCORE_OUTPUT_PARAM_HS_I_D\",\"LOD_JCW67_CS9_JRM_XB_CREDIT_OUTPUT_PARAM_HS_I_D\",\"LOD_JCW67_CS94_DMRZR_DTEST_CRYSTAL_V2_AUTO_OUTPUT_I_D\",\"LOD_JCW67_CS9_JRM_QZ_ZEBRASPREAD_OUTPUT_PARAM_HS_I_D\",\"LOD_JCW67_CS9_JRM_PORTRAIT_OUTPUT_PARAM_HS_I_D\",\"LOD_JCW64_CS94_DMRC_PD_FRAUD_A_LOAN_FINAL_SCORE_OUTPUT_I_M\",\"LOD_JCW67_CS9_JRM_FRAUD_SCORE_V1_OUTPUT_PARAM_HS_I_D\",\"LOD_JCW67_CS94_DMRZR_PD_CF_CRDT_CARD_FRAUD_SCORE_FINAL_OUTPUT_I_D\",\"LOD_JCW67_CS9_JRM_PANGU_SCORE_OUTPUT_PARAM_HS_I_D\",\"LOD_JCW67_CS4_JRM_DMRZR_BLACK_LIST_RISK_CDS_AUTO_OUT_A_M_PARAM\",\"LOD_JCW67_CS4_JRM_NEW_PORTRAIT_OUTPUT_PARAM_HS_I_D\"]";
        String t2 = "[\"LOD_JCW67_CS94_DMRZR_DTEST_CASH_LOAN_AUTO_OUTPUT_I_D\",\"LOD_JCW67_CS94_DMRZR_DTEST_CRYSTAL_V2_AUTO_OUTPUT_I_D\",\"LOD_JCW67_CS4_JRM_PANGUV3_SCORE_OUTPUT_PARAM_HS_I_D\",\"LOD_JCW67_CS4_JRM_DMRZR_BLACK_LIST_RISK_CDS_AUTO_OUT_A_M_PARAM\",\"LOD_JCW67_CS9_JRM_MULTI_LOAN_OUTPUT_PARAM_HS_I_D\",\"LOD_JCW67_CS94_DMRZR_GDJ_MODEL_FTC_OUTPUT_I_D\",\"LOD_JCW67_CS4_MULTIPLE_V3_SCORE_OUTPUT_PARAM_HS_I_D\",\"LOD_JCW67_CS9_JRM_XB_CREDIT_OUTPUT_PARAM_HS_I_D\",\"LOD_JCW67_CS9_JRM_PANGU_SCORE_OUTPUT_PARAM_HS_I_D\",\"LOD_JCW67_CS94_DMRZR_DTEST_KEQUN_LABEL_AUTO_OUTPUT_I_D\",\"LOD_JCW67_CS9_JRM_CREDIT_PORTRAIT_OUTPUT_PARAM_HS_I_D\",\"LOD_JCW67_CS9_JRM_QZ_ZEBRASPREAD_OUTPUT_PARAM_HS_I_D\",\"LOD_JCW67_CS94_DMRZR_DTEST_BLACK_LIST_V2_AUTO_OUTPUT_I_D\",\"LOD_JCW67_CS94_DMRZR_COMBINCARD_CREDIT_CARD_SCORE_AUTOBACK_I_D\",\"LOD_JCW64_CS94_DMRC_PD_FRAUD_A_LOAN_FINAL_SCORE_OUTPUT_I_M\",\"LOD_JCW67_CS9_JRM_FRAUD_SCORE_V1_OUTPUT_PARAM_HS_I_D\",\"LOD_JCW67_CS94_DMRZR_CASHLOANSC_B_CARD_SCORE_TRACEBACK_I_D\",\"LOD_JCW67_CS4_JRM_NEW_PORTRAIT_OUTPUT_PARAM_HS_I_D\",\"LOD_JCW67_CS9_JRM_PORTRAIT_OUTPUT_PARAM_HS_I_D\"]\n";

        List l1 = JSON.parseArray(t1, String.class);
        List l2 = JSON.parseArray(t2, String.class);

        for (Object o : l1) {
            if (!l2.contains(o)){
                System.out.println(o);
            }
        }

    }

}
